### PR TITLE
remove assertion when ignoring or repeating 0 calls

### PR DESCRIPTION
**Pull request by jpihl**
I think we've already had this discussion for the fifi library. But I'll try again, as it creates a bit of annoyance for me when i'm writing tests.

### CODE REVIEW

**Comment by mortenvp** [comment]
What is the usecase for ignoring zero calls?

**Comment by jpihl** [comment]
If I want the most recent call regardless of how many times the function has been called.

**Comment by mortenvp** [comment]
If you want the most recent call you have to know how many times it has been called? So if it has not been called why use ´repeat´ or ´ignore´?

**Comment by mortenvp** [comment]
What we could add to the API is an easy way to expect something on the last call:

```
stub::call<void(uint32_t,uint32_t)> function;

function(3,4);
function(4,3);
function(2,6);

assert(function.expect_last_call().with(2,6));
```

Or something similar.

**Comment by jpihl** [comment]
First of all; I really like  ``except_last_call``!

But I still want to explain myself.

The [readme states](https://github.com/steinwurf/stub#check-the-most-recent-function-call) that I can do this to get the most recent call:
```
stub::call<void(uint32_t,uint32_t)> function;
...
function.expect_calls().ignore(function.calls() - 1);
```
But that's only true if I've called the function at least twice. If I've only called the function once, that function call would be the most recent one. But I would get an assertion as ``function.calls() - 1 = 1 - 1 = 0``, and ``function.expect_calls().ignore(0)`` triggers an assert.

**Comment by mortenvp** [comment]
I'm still of the opinion that accepting `ignore(0)` or `repeat(0)` is allowing behavior that is logically hard to explain. Instead this indicates that we don't have an API that cleanly allows you to express you intent, namely to check only the last function call (without knowing exactly how many times it has been called). The other two are for cases where you know how many times something has been called.

**Comment by jpihl** [comment]
I'm looking into a different approach to solving this issue..

**Pull request closed without merging**
